import { Injectable, BadRequestException, InternalServerErrorException } from '@nestjs/common';
import { PrismaClient, DonationStatus } from '@prisma/client';
import { StripeService } from '../infrastructure/stripe.service';

export interface CreateCheckoutSessionInput {
  amount: number;
  ngoId: string;
  donorId: string;
  successUrl: string;
  cancelUrl: string;
}

export interface CreateCheckoutSessionOutput {
  sessionId: string;
  url: string;
}

@Injectable()
export class CreateCheckoutSessionUseCase {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly stripeService: StripeService,
  ) {}

  async execute(
    input: CreateCheckoutSessionInput,
  ): Promise<CreateCheckoutSessionOutput> {
    // Validate that NGO exists
    const ngo = await this.prisma.ngo.findUnique({
      where: { id: input.ngoId },
    });
    if (!ngo) {
      throw new BadRequestException('NGO not found');
    }

    // Validate that Donor exists
    const donor = await this.prisma.donor.findUnique({
      where: { id: input.donorId },
    });
    if (!donor) {
      throw new BadRequestException('Donor not found');
    }

    // Create Stripe session
    const session = await this.stripeService.createCheckoutSession({
      amount: input.amount,
      currency: 'usd',
      successUrl: input.successUrl,
      cancelUrl: input.cancelUrl,
      metadata: {
        ngoId: input.ngoId,
        donorId: input.donorId,
      },
    });

    // Best practice: Ensure URL was generated by Stripe
    if (!session.url) {
      throw new InternalServerErrorException('Failed to generate checkout URL from Stripe');
    }

    // Save donation as PENDING
    await this.prisma.donation.create({
      data: {
        amount: input.amount,
        ngoId: input.ngoId,
        donorId: input.donorId,
        status: DonationStatus.PENDING,
        stripeCheckoutSessionId: session.id,
      },
    });

    return {
      sessionId: session.id,
      url: session.url,
    };
  }
}