name: Terraform Security & Plan

on:
  pull_request:
    paths: [ 'terraform/**' ]

jobs:
  terraform-static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format & Init
        run: |
          cd terraform
          terraform fmt -check
          terraform init -backend=false
          terraform validate

      - name: Terraform Plan (Dry Run)
        run: |
          cd terraform
          terraform plan -no-color
        env:
          # Apenas para o plan não reclamar de variáveis faltando
          TF_VAR_db_password: dummy_pass
          TF_VAR_stripe_secret_key: dummy
          TF_VAR_stripe_webhook_secret: dummy
          TF_VAR_new_relic_license_key: dummy